bf16: true
beta: 0.1
do_eval: false
evaluation_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 1e-06
log_level: info
logging_steps: 10
lr_scheduler_type: linear
num_train_epochs: 1
optim: adamw_apex_fused
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "no"
save_total_limit: null
seed: 12357
warmup_ratio: 0.1