bos_token_id: 1
eos_token_id: 2
min_new_tokens: 1
max_new_tokens: 90
pad_token_id: 2
do_sample: false
num_beams: 1
suppress_tokens: [13]
temperature: 0.6
top_p: 0.9
context_aware_alpha: 0.5
contrastive_alpha: 0.1
contrastive_top_k: null
pmi_tau: 3.6
pmi_lambda: 0.066
mixture_mode: "hard"
mixture_alpha: 0.5
critic_model_path: null
critic_base_model_path: deberta-v3-base
critic_lambda: 0.25
critic_top_k: 5
critic_linear_warmup: true
